### ISSUE TITLE
why not separate the names Waterfox portable and Waterfox Classic portable

### ISSUE THREAD

**Issue by candrapersada** [Velgus/Scoop-Portapps#8]
separate the or add names Waterfox portable and Waterfox Classic portable in bucket
![image](https://user-images.githubusercontent.com/36833664/141936841-996c14c3-ac1f-4587-957c-002e6e1fd2b7.png)

**Comment by Velgus** [comment]
Didn't notice they were offering two versions in the same repo. Fixed.
